# Generated by Django 3.2.25 on 2025-06-29 12:50

import core.models.book_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.book_model.book_image_file_path),
        ),
    ]
