on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://devuser:devpass@localhost:5432/devdb"
      DEBUG: 1
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
